### PR TITLE
readme/manual

### PR DESCRIPTION
**Pull request by pluuto19**
modified the original manual a bit to suit our use case. let me know if i should change the getting started and customization section to remove some of the technical language. i couldnt come up with an ending section, lmk what to do about that. i havent yet gone thru talha's changes so idk what more functionality he has added which is why you wont find anything related to his changes. also, sorry if you guys are messaging on the whatsapp group, i broke my phone. ill see what i can do about that.

### CODE REVIEW

**Comment by alinadir44** [comment]
Talha's feature has now been merged. You can check it and update the manual accordingly. Meanwhile I'll go through the content you've already provided.

**Review by alinadir44 — CHANGES_REQUESTED** [review]
The readme is good. Regarding copilot, remove that part since we won't be using copilot. Please review your code changes so that they don't conflict after the last merged branch (Talha's). And do leave the Azire Static Web Apps part as it is, along with the GitHub Actions section

**Comment by pluuto19** [comment]
got it. i'll submit another pr in a few hours

**Comment by alinadir44** [comment]
Alright. Good luck with the phone situation too.
________________________________

**Comment by alinadir44** [comment]
Some updates:

- Please copy the Azure Static Web Apps part above GitHub Pages as is, from the main branch. Add it above the GitHub pages section you wrote.
- Add video snippet of GitHub Pages, from the main branch

**Comment by pluuto19** [comment]
okay. just woke up. let me get on it.

**Review by alinadir44 — APPROVED** [review]
Awesome. I'll share this with the presenters

**Pull request merged**
